### DISCUSSION TITLE
Add link in the resume

### DISCUSSION THREAD

**Discussion by FriederikeHanssen** [alshedivat/al-folio#1649] [Q&A] [answered]
Hi! I was wondering how to add links in my resume in the work section either in the resume.json or the cv.yml. In the yaml file, I tried with  in the cv.yml:

```
- title: Work
  type: time_table
  contents:
    - title: Associate Professor of Theoretical Physics
      institution: University of Zurich, Zurich, Switzerland
      year: 1909 - 1911
      description:
        - [project1](https://github.com/alshedivat/al-folio)
```

which doesn't work. Does anyone have any hints?

**Comment by FriederikeHanssen** [comment, marked as answer]
I figured it out:

```
- title: Work
  type: time_table
  contents:
    - title: Associate Professor of Theoretical Physics
      institution: University of Zurich, Zurich, Switzerland
      year: 1909 - 1911
      description:
        - <a href="https://github.com/alshedivat/al-folio">project1</a>
```

works
