### DISCUSSION TITLE
How do I change the size of the top/header menu font?

### DISCUSSION THREAD

**Discussion by aakashba** [alshedivat/al-folio#1666] [Q&A] [answered]
I would like to make the about/publications/projects font in the navigation header bigger, can anyone advice how to do that?

**Comment by riasat-sheikh** [comment, marked as answer]
You can do something like this inside the `_sass/_bass.css` file 

```css
// other codes here

// Navbar customization

.navbar {
  // other codes here
  font-size: desired size;
}

// other codes here
```
