### DISCUSSION TITLE
How to add a list of education and interests on the about page?

### DISCUSSION THREAD

**Discussion by junyuan-chen** [alshedivat/al-folio#1680] [Q&A] [answered]
Hi, thank you for developing this theme. I am entirely new to Jekyll. But, I want to create two lists for education and interest on the main page just like what I see here under the biography: https://academic-demo.netlify.app/

Could someone please show me the code needed for doing this?

**Comment by riasat-sheikh** [comment, marked as answer]
Check the [home.html](https://github.com/TheFermi0n/TheFermi0n.github.io/blob/master/_layouts/home.html) and [home.md](https://github.com/TheFermi0n/TheFermi0n.github.io/blob/master/_pages/home.md?plain=1) in my website's repo. And accordingly the profile section in [_base.css](https://github.com/TheFermi0n/TheFermi0n.github.io/blob/03b29e3d07f998be2ca409a4e26c1b6621d9cb50/_sass/_base.scss#L132). I am using the same layout you mentioned. 

Demo: https://thefermi0n.github.io

**Reply by junyuan-chen** [reply]
@TheFermi0n Hi, you already removed the code?

**Reply by riasat-sheikh** [reply]
I am really sorry. Actually, I deleted that repo and changed from al-folio to Hugo-academic. Feels much smoother. By the way, I am writing the code you need here itself.


### Home.html

you can change your `about.html` with these codes. That way you won't need to change the header file to accommodate the new page addition (`home.md`) as well.

```html
---
layout: default
---

<!-- home.html -->
<div class="post">
	
	<article class="home">
		<div class="row align-items-center">
      <div class="col-12 col-lg-4 center">
				{% if page.profile -%}
				<div class="profile">
					{%- if page.profile.image %} {%- assign profile_image_path = page.profile.image | prepend: 'assets/img/' -%}
					{% if page.profile.image_circular %} {%- assign profile_image_class = "img-fluid z-depth-1 rounded-circle"
					-%} {% else %} {%- assign profile_image_class = "img-fluid z-depth-1 rounded" -%} {% endif %} {% include
					figure.html path=profile_image_path class=profile_image_class alt=page.profile.image -%} {% endif -%}
				</div>
				{%- endif %}

				<div>
					<h2 class="post-title">
						{% if site.title == "blank" -%}
						{{ site.last_name }} <span class="font-weight-bold">{{ site.first_name }}</span> {{ site.middle_name }} {%- else -%}{{ site.title }}{%- endif %}
					</h2>

					<!-- description -->
					<p class="post-description">{{ page.subtitle }}</p>
					<!-- address -->
					{%- if page.profile.address %}
					<div class="address">{{ page.profile.address }}</div>
					{%- endif %}
					<!-- Social -->
					{%- if page.social %}
					<div class="social">
						<div class="contact-icons">{% include social.html %}</div>
					</div>
					{%- endif %}
				</div>
			</div>

			<div class="col-12 col-lg-8">
				<h2>Research Interest</h2>
				<p class="justify">{{ page.research }}</p>
				<div class="row">
					<div class="col-md-5">
						<div class="section-subheading">Interests</div>
							<ul class="ul-interests fa-ul mb-0">
						{% for interest in page.interests %}
								<li><i class="fa-li fa-solid fa-book"></i>{{ interest }}</li>
						{% endfor %}
							</ul>
					</div>
					
					<div class="col-md-7">
						<div class="section-subheading">Education</div>
						<ul class="ul-edu fa-ul mb-0">
							{% for edu in page.education %}
							<li><i class="fa-li fa-solid fa-graduation-cap"></i>
								<div class="description">
									<p class="course">{{ edu.course }}, {{ edu.year }}</p>
									<p class="institution">{{ edu.institution }}</p>
								</div>
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</article>
</div>

```

### Home.md

Similarly, change the about.md as below.
```md
---
layout: home
title: Home
permalink: /
subtitle: 

profile:
  image: prof_pic.jpg
  image_circular: true # crops the image to make it circular
  address: >
    <p>Your address5</p>

social: true  # includes social icons at the bottom of the page
research: |
  your biography or research interest here
interests:
  - ""
education:
  - course: 
    institution: 
    year:
---
```

### _base.scss

Add the following inside your `_base.scss` file

```css
//Profile
.center {
  text-align: center !important;
}
.justify {
  text-align: justify !important;
}
.section-subheading {
  font-size: 1.25rem;
  font-weight: 700;
  margin-top: 1rem;
  margin-bottom: .5rem;
}


.ul-edu {
  list-style: none;
  
  li {
    position: relative;
    padding: 0 15px 4px 3px !important;
  }
}

.home {
  .description {
    p {
      margin: 0;
    }
    .institution {
      font-size: 0.875rem;
      color: var(--global-text-color-light);
    }
  }
  .address {
    margin-bottom: 5px;
    margin-top: 5px;
    
    p {
      display: inline-block;
      margin: 0;
      font-family: monospace;
      font-size: 0.875rem;
    }
  }

}

//other codes here

@media (min-width: 576px) {
  .profile {
      width: 70%;

    .address {
      p {
        display: block;
      }
    }
  }
}

//other codes
```
