### DISCUSSION TITLE
ai-folio permalink with a name of a repository

### DISCUSSION THREAD

**Discussion by victorballester7** [alshedivat/al-folio#1864] [Q&A] [answered]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Can I add a menu in the navigation bar that has as permalink the name of one of my repositories? My domain of the website is github.io, so it seems to intercept with the possible website from Github created from the other repository. And right now, if I do that, I get the error 404, site not found.

**Comment by victorballester7** [comment, marked as answer]
Ok, I think I've already solved (or at least kind of). Maybe it's not the most elegant solution, but it works fine... In the `deploy.yml` I added the following code

```
##### This is the part that I added #####
- name: Checkout gh-page 🛎️
  uses: actions/checkout@v3
  with:
    ref: gh-pages
- name: Copy files to another repository
  uses: lubu12/copy-files-to-repository@v1
  # Recall that you have to create (now it's created) a secret called API_TOKEN_GITHUB with a token with repo permissions and then you have to add it to the repository secrets. See the repository of lubu12 for more information.
  env:
    API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  with:
    source-files: complete-summaries/index.html assets
    destination-username: victorballester7
    destination-repository: complete-summaries
    destination-directory:
    destination-branch: main
    # from-container: false
    commit-email: victor.ballester.ribo@gmail.com
    commit-message: "Update html and assets folder file"
#########################################
```

just after the step `Deploy`. This copies the `index.html` and all the necessary assets (maybe all of them are not necessary, but doesn't matter...) to the other repository, and commit & push them. 

If someone has a better solution, feel free to notify me!!! :smile:
