### DISCUSSION TITLE
Validity of `enable` options of `latest_posts` in '_config.yml'

### DISCUSSION THREAD

**Discussion by DrummyCrane** [alshedivat/al-folio#2043] [Q&A] [answered]
**Question**: 
I wonder what is the purpose of `enable` of `latest_posts` in **`_config.yml`** ?

**Detail**:
I found that `news: true` and `latest_posts: true` in **`about.md`** make announcements and posts visible.
```
news: true  # includes a list of news items
latest_posts: true  # includes a list of the newest posts
```

And there are `enable` options for `announcements` and `latest_posts` in **`_config.yml`**.
```
announcements:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 news items
  limit: 5 # leave blank to include all the news in the `_news` folder

latest_posts:
  enabled: true
  scrollable: true # adds a vertical scroll bar if there are more than 3 new posts items
  limit: 3 # leave blank to include all the blog posts
```

Also, with `about.html` in below, I found that the visibility of the `news` is determined by both `news` in **`about.md`** and `enable` of `announcements` in **`_config.yml`**.
```
          <!-- News -->
          {% if page.news and site.announcements.enabled -%}
            <h2><a href="{{ '/news/' | relative_url }}" style="color: inherit;">news</a></h2>
            {%- include news.html limit=true %}
          {%- endif %}
```

However, `latest_posts` is controlled by the parameter **only** in **`about.md`**.
```
          <!-- Latest posts -->
          {% if page.latest_posts -%}
            <h2><a href="{{ '/blog/' | relative_url }}" style="color: inherit;">latest posts</a></h2>
            {%- include latest_posts.html %}
          {%- endif %}
```

I didn't find differences when I disable `latest_posts` in **`_config.yml`**.
Is it okay if I enable this parameter in **`_config.yml`** while disabling it in **`about.md`**?
