### DISCUSSION TITLE
"Failed: Cannot find file" when deploying

### DISCUSSION THREAD

**Discussion by yassinetb** [alshedivat/al-folio#2239] [Q&A] [answered]
I am facing an issue with what seems to be a wrong way of dealing with reference links, where Github refuses to deploy the website because it cannot find the link. Here is the error and the relevant code: 

Also, is there a way to debug these things without losing time deploying to GitHub? All these things run perfectly on my docker container.

Errors:

```
Errors in _pages/open_projects.md
[ERR] file:///home/runner/work/yassinetb.github.io/yassinetb.github.io/_pages/%7B%7B%20project.url%20|%20relative_url%20%7D%7D | Failed: Cannot find file


```

Relevant code: 

```
{% for project in sorted_projects %}
  <div class="project">
    <a href="{{ project.url | relative_url }}">
      <h2 class="project-title">{{ project.title }}</h2>
    </a>
    {% if project.authors %}
    <p class="project-info"><strong>Supervisors:</strong> 
        {% for supervisor in project.authors %}
        {{ supervisor.name }}
        {% unless forloop.last %}, {% endunless %}
        {% endfor %}
    </p>
    {% endif %}
    {% if project.type %}
    <p class="project-info"><strong>Project Type:</strong> {{ project.type | join: ', ' }}</p>
    {% endif %}
    {% if project.duration %}
    <p class="project-info"><strong>Project Duration:</strong> {{project.duration}}</p>
    {% endif %}
  </div>
  <hr> <!-- Separator -->
{% endfor %}
```

with the data file:

```
---
layout: distill
title: Building some projoct
description: 
img: assets/img/ARC.png
importance: 1
category: open
show: true
permalink: /arc_project/
url: /arc_project/
type:
    - Thesis
authors:
  - name: Yassine Taoudi-Benchekroun
  - url: "mailto:ytaoudi@student.ethz.ch"
    affiliations:
      name: Institute of Neuroinformatics
---
```

Any ideas what I'm doing wrong here?
