### DISCUSSION TITLE
Error with local deployment and docker : Error in request.rb

### DISCUSSION THREAD

**Discussion by hrositi** [alshedivat/al-folio#2279] [Q&A] [answered]
The error when using Docker compose up :
 _"Fetching external posts from :"
jekyll-1  | /var/lib/gems/3.0.0/gems/httparty-0.21.0/lib/httparty/request.rb:87:in `path=': bad argument (expected URI object or URI string) (ArgumentError)_

Deployment on Github pages is working fine but not convenient to customize.

thank you in advance.

**Comment by george-gca** [comment, marked as answer]
Related issue #1696

Comment out these lines in your `_config.yml` instead of leaving it empty:

```yml
# External sources.
# If you have blog posts published on medium.com or other external sources,
# you can display them in your blog by adding a link to the RSS feed.
external_sources:
  - name: 
    rss_url:
```
