### DISCUSSION TITLE
How to create new collections? What are the collection's fields?

### DISCUSSION THREAD

**Discussion by ztjona** [alshedivat/al-folio#2369] [Q&A] [answered]
Hi, 

I want to add a section of Teaching, not sure how to do it, in ``_config.yml``.
```
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
```

 I think I have to add something like this three rows? Where is the docs of the ``collections``??

```
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
```

But only adding this does not work. 
I created a ``teaching.md`` in ``/_pages/`` that is very similar to ``projects.md``. And also created a folder ``/_teaching/`` with a ``1_teaching.md``. 

What I have to change in this file?
