### DISCUSSION TITLE
Blog articles not referenced on search engines

### DISCUSSION THREAD

**Discussion by yassinetb** [alshedivat/al-folio#2585] [Q&A] [answered]
Hi all, 

While my website is well referenced on Google etc.. and pops up well when searching, I can not find my blog articles on Google, despite them having been published for several months. 

I wonder if there is any configuration I'm not setting properly for the blog articles to be referenced properly. For reference, here is the header of my blog files - perhaps I'm missing a field here to optimize for referencing? 

Thank you!

```
---
layout: distill
title:  Some blog title
show: true
category: open
related_publications: false
date: 2024-07-01
featured: true
toc:
  - name: Some Section
  - name: Some other section
---
```
