### DISCUSSION TITLE
YouTube embed too small

### DISCUSSION THREAD

**Discussion by liberomureddu** [alshedivat/al-folio#2683] [Q&A]
Hi everybody! 
First post here, and I wanted to thank all the people who have made this wonderful theme!

I have a question about embedding YouTube videos.
I used the code as in [here](https://github.com/alshedivat/al-folio/blob/master/_posts/2023-04-24-videos.md)
```html
<div class="row">
    <div class="col-sm mt-3 mt-md-0">
        {% include video.liquid path="https://www.youtube.com/embed/ZbEWNc4kuJs?si=tmlEkenbuhN63TJQ" class="img-fluid rounded" %}
    </div>
</div>
```

but the resulting embedded video is too small. Moreover its upper and lower borders are slightly cropped. I tried to add width and height, played with column sizes, edited the css directly in the browser, but I haven't found any solution.

I then added to my page the code found [here](https://github.com/codepo8/youtube-embed/blob/main/youtube.html), and it works fine.
```html
<div class="embed-container">
    <iframe width="640" height="390" 
    src="https://www.youtube.com/embed/ZbEWNc4kuJs?si=tmlEkenbuhN63TJQ" 
    frameborder="0" allowfullscreen></iframe>
</div>
<style>
.embed-container {
  position: relative;
  padding-bottom: 56.25%;
  height: 0;
  overflow: hidden;
  max-width: 100%;
}
.embed-container iframe,
.embed-container object,
.embed-container embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
</style>
```
However, I would like to be able to have a grid of YouTube videos, something I cannot do anymore with this workaround.
Any suggestion?
Thank you in advance for your time.

**Comment by liberomureddu** [comment]
I worked a bit more on the YouTube embed solution, and it seems it work well:
1. I added the following code to_sass/_layout.scss
<details> <summary> code </summary> 

```scss
.embed-container { 
  position: relative;
  padding-bottom: 56.25%;
  height: 0;
  overflow: hidden;
  max-width: 100%;
}
.embed-container iframe,
.embed-container object,
.embed-container embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```
</details>

2. I modified _includes/video.liquid as follows:

<details> <summary> code </summary> 

```liquid
{% assign extension = include.path | split: '.' | last %}

<figure class="embed-container">
  {% if extension == 'mp4' or extension == 'webm' or extension == 'ogg' %}
    <video
      src="{% if include.cache_bust %}{{ include.path | relative_url | bust_file_cache }}{% else %}{{ include.path | relative_url }}{% endif %}"
      {% if include.class %}
        class="{{ include.class }}"
      {% endif %}
      {% if include.width %}
        width="{{ include.width }}"
      {% else %}
        width="auto"
      {% endif %}
      {% if include.height %}
        height="{{ include.height }}"
      {% else %}
        height="auto"
      {% endif %}
      {% if include['min-width'] %}
        min-width="{{ include.min-width }}"
      {% endif %}
      {% if include['min-height'] %}
        min-height="{{ include.min-height }}"
      {% endif %}
      {% if include['max-width'] %}
        max-width="{{ include.max-width }}"
      {% endif %}
      {% if include['max-height'] %}
        height="{{ include.max-height }}"
      {% endif %}
      {% if include.title %}
        title="{{ include.title }}"
      {% endif %}
      {% if include.alt %}
        alt="{{ include.alt }}"
      {% endif %}
      {% if include.autoplay %}
        autoplay
      {% endif %}
      {% if include.controls %}
        controls
      {% endif %}
      {% if include.loop %}
        loop
      {% endif %}
      {% if include.muted %}
        muted
      {% endif %}
      {% if include.poster %}
        poster="{{ include.poster }}"
      {% endif %}
    />

  {% else %}
    <iframe
      src="{{ include.path }}"
      {% if include.class %}
        class="{{ include.class }}"
      {% endif %}
      frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
      allowfullscreen
      {% if include.width %}
        width="{{ include.width }}"
      {% else %}
        width="100%"
      {% endif %}
      {% if include.height %}
        height="{{ include.height }}"
      {% else %}
        height="100%"
      {% endif %}
      {% if include['min-width'] %}
        min-width="{{ include.min-width }}"
      {% endif %}
      {% if include['min-height'] %}
        min-height="{{ include.min-height }}"
      {% endif %}
      {% if include['max-width'] %}
        max-width="{{ include.max-width }}"
      {% endif %}
      {% if include['max-height'] %}
        height="{{ include.max-height }}"
      {% endif %}
      {% if include.alt %}
        alt="{{ include.alt }}"
      {% endif %}
      {% if include.title %}
        title="{{ include.title }}"
      {% endif %}
    />
  {% endif %}
  {% if include.caption %}
    <figcaption class="caption">{{ include.caption }}</figcaption>
  {% endif %}
</figure>
```
</details>

Everything seems to work, but it'd be great to hear the opinion of more experienced people.
One can see the effect on the [blog post entry about videos](https://liberomureddu.github.io//blog/2023/videos/), in which the YouTube videos are at the same size as the locally stored videos.

**Reply by george-gca** [reply]
I am not a prolific web dev, but some things are a little confusing, like:

```css
.embed-container { 
  position: relative;  // why set this when you override it next?
  padding-bottom: 56.25%;  // isn't this too much padding?
  height: 0;  // why set this when you override it next?
}
.embed-container iframe,
.embed-container object,
.embed-container embed {
  position: absolute;  // you override the relative position
  height: 100%;  // you override the height
}
```

also, setting [position absolute](https://www.w3schools.com/css/css_positioning.asp) makes it hard to  understand it. What is it relative to in this case? This seems kind of the case where it works and idk why.
