### DISCUSSION TITLE
Adding custom_social doesn't seem to work

### DISCUSSION THREAD

**Discussion by experimentalsoundingfinland** [alshedivat/al-folio#2974] [Q&A] [answered]
Hi! 
I'm trying to add a custom_social in _data/socials.yml (for Pixelfed).
As it didn't work I've been searching for custom_social elsewhere in the repository but couldn't find any result. I searched in [social.liquid](https://github.com/alshedivat/al-folio/blob/d3402d0379d1e346417e012a9f22c990b948ab1a/_includes/social.liquid) and [search.liquid.js](https://github.com/alshedivat/al-folio/blob/d3402d0379d1e346417e012a9f22c990b948ab1a/_scripts/search.liquid.js) and couldn't find any reference of custom_social. 

Am I missing something obvious? Thanks for any help!

**Comment by george-gca** [comment]
Yes, you are. If you check the first line in `_includes/social.liquid`:

https://github.com/alshedivat/al-folio/blob/d3402d0379d1e346417e012a9f22c990b948ab1a/_includes/social.liquid#L1

which means we loop through all the socials in `_data/socials.yml`. If is not a know social, it falls in the else case:

https://github.com/alshedivat/al-folio/blob/d3402d0379d1e346417e012a9f22c990b948ab1a/_includes/social.liquid#L95-L109

**Reply by liberomureddu** [reply]
That's what I understood. Yet, when I add the following code (or uncomment the default one) in `socials.yml`, nothing happens:
```yml
custom_social: Pixelfed # can be any name here other than the ones already defined above
   logo: https://github.com/pixelfed/brand-assets/blob/9c38fdcdafdb37c446fa4514cefa1b025c783f99/logo/symbolic.svg  # can be png, svg, jpg
   title: Pixelfed
   url: https://pixl.fi/i/web/profile/787587638804833518 # https://www.alberteinstein.com/
  ```
