### DISCUSSION TITLE
How to create a new collection to display a page which is similar to projects page

### DISCUSSION THREAD

**Discussion by Qiuyi-Hong** [alshedivat/al-folio#568] [Q&A] [answered]
Hello,

I would like to create a new page that is similar to the projects page. However, I am not sure how to edit the _config.yml file, and create a new page in the _pages folder. If anyone comes up with an idea, I appreciate it. 

Thanks

**Comment by rqnguyen100** [comment]
Struggled with this problem for a while. You can just copy and paste the project.md file in _pages for a new page. Don't create a new folder like _project. Keep all your projects in that folder and use different categories. The projects with a certain category will show up on their respective pages.

**Reply by RehmatSChawla** [reply]
That's very elegant, I love it!

**Comment by wyhallenwu** [comment, marked as answer]
I have successfully achieved this goal. And I modify three files.

First, you need to add a new collection(for me I create a new collection named albums) in the collections in _config.yml(around line 167)
```
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  albums:
    output: true
    permalink: /albums/:path/
```

Then, you have to make a new folder and its name should be the `_albums`. It plays the same role as folder `_projects`. 

Finally, you need to create a file `albums.md` in the `_pages`. And copy the content of the file `projects.md` to it. But there are two places you have to modify. 
around line 18 and line 40 (in copied albums.md file), change the `site.projects` to `site.albums`

If my answer is not clear, you can check my modified repo `https://github.com/wyhallenwu/wyhallenwu.github.io`.
