### DISCUSSION TITLE
How to format Teaching page

### DISCUSSION THREAD

**Discussion by Emadmasroor** [alshedivat/al-folio#618] [Q&A] [answered]
I would like to create a page similar to the style/formatting of [https://maruan.alshedivat.com/teaching/](https://maruan.alshedivat.com/teaching/).

@alshedivat, Could you please share the Markdown code that you used to generate the page? I have tried looking in this repository but I believe your own website is stored somewhere else.

**Comment by mbarbetti** [comment]
@alshedivat, indeed your website is so cool! If you don't mind sharing also the Markdown code use to generate the **code** page, I would really appreciate it!

**Comment by alshedivat** [comment]
check out https://github.com/eaplatanios/eaplatanios.github.io/blob/src/_pages/teaching.md (rendered page here: http://platanios.org/teaching/), which very similar to mine. it would require updating markdown and some of the styles as well.

**Reply by Emadmasroor** [reply]
That page seems to be written in pure html (if I look at the 'raw' code). Could you point me to some resources to learn how to make Markdown generate the html for me?

**Comment by jesse-wei** [comment, marked as answer]
I copied @ alshedivat's teaching page's raw HTML into my own [teaching page](https://jessewei.dev/teaching/) ([code](https://github.com/jesse-wei/jesse-wei.github.io/blob/master/_pages/teaching.md), [raw](https://raw.githubusercontent.com/jesse-wei/jesse-wei.github.io/master/_pages/teaching.md)). The page looks identical except for some color changes, and I also added some `<br>`s between links in the table.

The badge and table background colors weren't working correctly on theme toggle, so I used inspect element and found that 2 relevant lines of relevant CSS seem to have been removed from the repo since he made his site. I pasted these two lines into `_sass/_base.scss` in the `.card` class. [Code](https://github.com/jesse-wei/jesse-wei.github.io/blob/master/_sass/_base.scss) ([raw](https://raw.githubusercontent.com/jesse-wei/jesse-wei.github.io/master/_sass/_base.scss))

```scss
/**
 * Source: https://maruan.alshedivat.com/assets/css/main.css
 */

  /* Modified --global-bg-color (used in Maruan's site) to --global-card-bg-color. */
  /* If you use --global-bg-color, you'll need to change some other CSS. */
  .list-group-item {
    background-color: var(--global-card-bg-color); border-color: var(--global-divider-color);
  }
  .badge {
    background-color: var(--global-theme-color); padding-left: 1rem; padding-right: 1rem;
  }
```

My current commit is [1dfe66b](https://github.com/jesse-wei/jesse-wei.github.io/commit/1dfe66b38f146a724084cdc8e10bb6438e7ba711), if I end up changing this page.
