### DISCUSSION TITLE
How to create another page with pagination like the 'blog' page ?

### DISCUSSION THREAD

**Discussion by AtivJoshi** [alshedivat/al-folio#678] [Q&A] [answered]
I created a new folder called `al-folio/misc` and a file `misc/index.html`, a new folder `_extras` that contains all the posts that are to be displayed in the misc section and, created a new collection called `extras` in  `_config.yml` file. The `misc/index.html` has the following content:

```
---
layout: default 
title: miscs
nav: true
nav_order: 3
pagination:
  enabled: true
  collection: extras
  permalink: /page/:num/
  per_page: 5
  sort_field: date
  sort_reverse: true
  trail:
    before: 1 # The number of links before the current page
    after: 3  # The number of links after the current page
---
Some text.

<!-- custom liquid code -->
```

Now, no matter what I put after the front-matter in `misc/index.html`, the misc page is always built according to the `blog/index.html` (i.e. the "Some text" string right after the front-matter is not displayed, instead the heading of `blog/index,html` is displayed ).  Although the articles in the `_extras` directory are all displayed correctly with pagination, the formatting is just like the "blog" page and I cannot change it. What should I do to customize the `misc` page?  Note that if I remove all the Liquid syntax, then the "Some text" string is displayed and the list of articles with pagination is not displayed.

[Link to my relevant commit](https://github.com/AtivJoshi/al-folio/tree/b62b9b3cf7ab573363252ef545f2b7a47ff4e8a3)
