### ISSUE TITLE
Tables with Bootstrap Tables doesn't display top border on dark mode

### ISSUE THREAD

**Issue by george-gca** [alshedivat/al-folio#1425]
**Acknowledge the following**
- [X] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [X] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
Tables with Bootstrap Tables doesn't display top border on dark mode.

**To Reproduce**
1. Go to the [related blog post](https://alshedivat.github.io/al-folio/blog/2023/tables/)

**Expected behavior**
Top border shown as in light mode.

**Screenshots**
Light mode:

![image](https://github.com/alshedivat/al-folio/assets/31376482/9b1ba3f9-c3b1-41a5-8166-26be57a38c08)

Dark mode:

![image](https://github.com/alshedivat/al-folio/assets/31376482/3edb5b14-cbda-4458-8661-d441b2b08c8b)

**Comment by george-gca** [comment]
I still can't figure out how exactly this happens, but when I comment the mdb css line from `head.html`

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/mdbootstrap@{{ site.mdb.version }}/css/mdb.min.css" integrity="{{ site.mdb.integrity.css }}" crossorigin="anonymous" />
```

The table shows as expected. Anyone have any idea what exactly changes this?

**Comment by george-gca** [comment]
I figured this specific setting inside `mdb.css`:

```css
table.table thead th {
    border-top: none;
}
```

This is the rule messing it up in dark mode. I just don't know how to unset it correctly in our `_base.scss` so to overwrite this.

**Comment by lancewilhelm** [comment]
I think I have found a solution, add the following border line to `.table-dark` in `_bass.scss`. Fixes the issue.

```scss
.table-dark {
  background-color: transparent;
  border: 1px solid var(--global-divider-color) !important;
}
```
PR #1762

**Comment by lancewilhelm** [comment]
I think I found a solution, we must override the bootstrap `.table-bordered` settings for `.table-dark`

```scss
.table-dark {
  background-color: transparent;
  &.table-bordered{
    border: 1px solid var(--global-divider-color) !important;
  }
}
```
PR: #1763
