### ISSUE TITLE
On Adding Hashnode RSS: Liquid Exception: Numerical argument is out of domain - sqrt in /SwayamInSync.github.io/_layouts/post.html

### ISSUE THREAD

**Issue by SwayamInSync** [alshedivat/al-folio#1828]
Made these changes to re-create the error
```yml
# External sources.
# If you have blog posts published on medium.com or other external sources,
# you can display them in your blog by adding a link to the RSS feed.
external_sources:
  - name: Hashnode.com
    rss_url: https://swayam-blog.hashnode.dev/rss.xml
```
