### ISSUE TITLE
successfully compiled but no connection [Windows 11, Docker]

### ISSUE THREAD

**Issue by congzhang-linguist** [alshedivat/al-folio#1916]
Hi
I pulled the repo using the 'use this template' function today. Then followed the docker installation instructions on a Windows 11 machine.
The only change I've made so far is deleting the post with the diagram.

After compilation, everything seems to be fine. No errors throughout.
![image](https://github.com/alshedivat/al-folio/assets/112589549/10e74a3d-cd6b-450a-bec7-7143ef1b657c)

But when I clicked on the link, it does not connect:
![image](https://github.com/alshedivat/al-folio/assets/112589549/d71d2ac4-c64a-4be3-974f-eabbe2e712e0)

I also tried updating the `docker-compose.yml` file following a solution I saw in another issue but no luck:

```
version: "3"

services:
  jekyll:
    image: amirpourmand/al-folio
    command: bundler exec jekyll serve --watch --port=8080 --host=0.0.0.0 --verbose
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
```

Could you advise what might have been wrong? Thanks
