### ISSUE TITLE
Deploy failing -- Vendor Bundle?! or?!

### ISSUE THREAD

**Issue by HoffmanGeospatial** [alshedivat/al-folio#3045]
### Have you checked that your issue isn't already filed?

- [x] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] Yes, I have checked that this issue isn't already filed.

### Bug description

Deploy fail at Install and Build phase (GH Pages)

### How to reproduce the bug

I have been following all the provided documentation: used the Docker dev container in VS Code like INSTALL.md describes and had success seeing my custom site stuff on my localhost browser preview. However, after about a dozen tries deploying repo on GitHub Pages -- even using the GH Copilot AI chatbot "Explain Error" feature each time too!! -- the fails all seem to occur after a minute or two of inactivity at the [NbConvertApp] lines. But... I know better than to believe that's the sole source of the fail issue.

Below I will paste lines number 741 through the end of the deploy log to show that spot where it suddenly all hangs up for a couple minutes and then spits out the remaining lines with oh so helpful last one:
"Error exit code 1".

I am at this point so stumped and feeling defeated and exhausted. 

### Error messages and logs

```
36 │   @return unquote("\"")+unquote(str-insert($str, "\\", 1))+unquote("\"")
   │                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    tabler-icons/tabler-icons.scss 36:33                         unicode()
    tabler-icons/tabler-icons.scss 40:15                         @import
    /home/runner/work/acfolio/acfolio/assets/css/main.scss 19:3  root stylesheet
WARNING: 39 repetitive deprecation warnings omitted.
Run in verbose mode to see all warnings.
[NbConvertApp] Converting notebook /tmp/jekyll-jupyter-notebook20250305-3585-qaeecl.ipynb to html
/opt/hostedtoolcache/Python/3.13.2/x64/lib/python3.13/site-packages/nbconvert/filters/highlight.py:71: UserWarning: IPython3 lexer unavailable, falling back on Python 3
  return _pygments_highlight(
                    ------------------------------------------------
      Jekyll 4.3.4   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/uglifier-4.2.1/lib/uglifier.rb:291:in `parse_result': Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true). (Uglifier::Error)
--
  1 // get the ninja-keys element
 => const ninja = document.querySelector('ninja-keys');

  3 
  4 // add the home and posts menu items
  5 ninja.data = [{
  6     id: "nav-about",
  7     title: "About",
  8     section: "Navigation",
  9     handler: () => {
 10       window.location.href = "/acfolio/";
==
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/uglifier-4.2.1/lib/uglifier.rb:221:in `run_uglifyjs'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/uglifier-4.2.1/lib/uglifier.rb:166:in `compile'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:102:in `output_js'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:21:in `output_compressed'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:182:in `write'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:231:in `block in write'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:363:in `block in each_site_file'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:363:in `each'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:363:in `each_site_file'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:230:in `write'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:82:in `process'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:28:in `process_site'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/commands/build.rb:65:in `build'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/commands/build.rb:36:in `process'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `each'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.4/exe/jekyll:15:in `<top (required)>'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `load'
	from /home/runner/work/acfolio/acfolio/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/cli/exec.rb:59:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/cli/exec.rb:59:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/cli.rb:452:in `exec'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/vendor/thor/lib/thor.rb:538:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/cli.rb:35:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/cli.rb:29:in `start'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/exe/bundle:28:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.6.2/exe/bundle:20:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/bin/bundle:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/bin/bundle:25:in `<main>'
Error: Process completed with exit code 1.

```

### What operating system are you using?

Windows

### Where are you seeing the problem on?

Deployed site

### More info

Here's my slightly differing `deploy.yml`:

```
`name: Deploy site

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "_sass/**"
      - "**.bib"
      - "**.html"
      - "**.js"

      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/broken-links.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      #- "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
      - "!CONTRIBUTING.md"
      - "!CUSTOMIZE.md"
      - "!FAQ.md"
      - "!INSTALL.md"
      - "!README.md"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "_sass/**"
      - "**.bib"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "Gemfile"
      - "Gemfile.lock"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/broken-links.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      #- "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
      - "!CONTRIBUTING.md"
      - "!CUSTOMIZE.md"
      - "!FAQ.md"
      - "!INSTALL.md"
      - "!README.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.5"
          bundler-cache: true
      - name: Update Bundler
        run: gem install bundler 
      - name: Setup Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
        #- name: Debug Jekyll
          #run: |
            #cat _config.yml
            #bundle list
      - name: Update _config.yml ⚙️
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          propertyPath: "giscus.repo"
          value: ${{ github.repository }}
      - name: Install and Build 🔧
        run: |
          sudo apt-get update && sudo apt-get install -y imagemagick
          pip3 install --upgrade nbconvert
          export JEKYLL_ENV=production
          bundle exec jekyll build --trace
      - name: Purge unused CSS 🧹
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js
      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder:  _site`
```

**Comment by george-gca** [comment]
We recommend first setting up your site remotely, deploy an exact copy of the demo site, and only then clone it locally and customize it. Also do small, incremental updates, so it is easier to pinpoint which changes caused the issue.

At this point it is hard to find your issue. My recommendation is, copy your code locally, then start all over. Do the recommended steps first, then try to add your changes step by step, always checking if the site builds correctly on the GitHub pages.

**Comment by HoffmanGeospatial** [comment]
Hi George, thanks for the response. I have followed your instructions. 
It now appears that "Uglifier" is causing my deploy to fail.
Is that plug-in *absolutely* necessary??

**Comment by george-gca** [comment]
Uglifier? Can you provide more information?

It is a dependency of `jekyll-minifier` I believe. We use it to minify some of the assets, like the css and js.

**Comment by Seondong** [comment]
jekyll-minifier does not support ES6+
How should I handle this?

_config.yml
```
# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ['robots.txt']
  js_compressor: null
  uglifier_args:
    harmony: true
```

Deploy site error message

```  =>     const selectedIndex = parseInt(stageSelect?.value || 0);```

```
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/uglifier-4.2.1/lib/uglifier.rb:221:in `run_uglifyjs'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/uglifier-4.2.1/lib/uglifier.rb:166:in `compile'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:102:in `output_js'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:210:in `write'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:231:in `block in write'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:358:in `block (2 levels) in each_site_file'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:357:in `each'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:357:in `block in each_site_file'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:356:in `each'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:356:in `each_site_file'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:230:in `write'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/site.rb:82:in `process'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:28:in `process_site'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:65:in `build'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:36:in `process'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `each'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-4.2.2/exe/jekyll:15:in `<top (required)>'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `load'
	from /home/runner/work/seondong.github.io/seondong.github.io/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/cli.rb:455:in `exec'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/cli.rb:35:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/cli.rb:29:in `start'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.16/exe/bundle:28:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/3.3.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.16/exe/bundle:20:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/bin/bundle:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/bin/bundle:25:in `<main>'
Error: Process completed with exit code 1.

```
