### ISSUE TITLE
Use jekyll_dynamic_assets to handle head assets

### ISSUE THREAD

**Issue by MUmarShahbaz** [alshedivat/al-folio#3215]
### Have you checked that your feature request isn't already filed?

- [x] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [x] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

Al-folio currently relies on a lot of boolean from the page front matter to decide which head assets to use. Using JDA can clean up the process a bit and make it easier for the user to customize.

### Pitch

```yaml
dynamic_assets:
  absolute: true
  source:
    font_awesome: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/
    bootstrap: https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist
  master:
   - bootstrap<</js/bootstrap.bundle.min.js::defer-js
   - font_awesome<<css/all.min.css
   - master.css
  formats:
    defer-js: <script defer src="%s"></script>
```

Here is an example from what I'm currently using. Using the jekyll_dynamic_assets ruby gem will allow easier handling of head assets. The gem also allows presets!!

Here is a list of features
- Auto Head Assets
- Custom formatting
- Custom Sources
- Absolute, Relative and External use
- Simple usage

Package URL: https://rubygems.org/gems/jekyll_dynamic_assets

### Alternatives

The alternative is to continue using the current liquid maze.
